### ISSUE TITLE
LC model does currently not support multiple variables to minimize

### ISSUE THREAD

**Issue by cod3monk** [RRZE-HPC/kerncraft#60]
Reproduce by using L,M,N in 3d-long-range-stencil.

**Comment by sguera** [comment]
I think I hit this error right now, but not in a long range stencil.

Command run:
``
kerncraft -p LC 3d-1r-isotropic-constant-star-stencil.c -m BroadwellEP_E5-2697_CoD.yml -D M 140 -D N 140 -D P 140
``

Error:
``
-------------------------------------- LC --------------------------------------
Traceback (most recent call last):
  File "/users/staff/ifi/guerrera/STEMPEL_DEV/stempelenv/bin/kerncraft", line 11, in <module>
    sys.exit(main())
  File "/users/staff/ifi/guerrera/STEMPEL_DEV/stempelenv/local/lib/python2.7/site-packages/kerncraft/kerncraft.py", line 289, in main
    run(parser, args)
  File "/users/staff/ifi/guerrera/STEMPEL_DEV/stempelenv/local/lib/python2.7/site-packages/kerncraft/kerncraft.py", line 255, in run
    model.analyze()
  File "/users/staff/ifi/guerrera/STEMPEL_DEV/stempelenv/local/lib/python2.7/site-packages/kerncraft/models/layer_condition.py", line 239, in analyze
    self.results = self.calculate_cache_access()
  File "/users/staff/ifi/guerrera/STEMPEL_DEV/stempelenv/local/lib/python2.7/site-packages/kerncraft/models/layer_condition.py", line 200, in calculate_cache_access
    'eq': sympy.solve(inequality, *self.kernel.constants.keys(), dict=True)
  File "/users/staff/ifi/guerrera/STEMPEL_DEV/stempelenv/local/lib/python2.7/site-packages/sympy/solvers/solvers.py", line 848, in solve
    return reduce_inequalities(f, symbols=symbols)
  File "/users/staff/ifi/guerrera/STEMPEL_DEV/stempelenv/local/lib/python2.7/site-packages/sympy/solvers/inequalities.py", line 701, in reduce_inequalities
    rv = _reduce_inequalities(inequalities, symbols)
  File "/users/staff/ifi/guerrera/STEMPEL_DEV/stempelenv/local/lib/python2.7/site-packages/sympy/solvers/inequalities.py", line 622, in _reduce_inequalities
    symbol of interest'''))
NotImplementedError: 
inequality has more than one symbol of interest
``

Content of 3d-1r-isotropic-constant-star-stencil.c:
``
double a[M][N][P];
double b[M][N][P];
double c0;
double c1;

for(int k=1; k < M-1; k++){
for(int j=1; j < N-1; j++){
for(int i=1; i < P-1; i++){
b[k][j][i] = c0 * a[k][j][i]
+ c1 * ((a[k][j][i-1] + a[k][j][i+1]) + (a[k-1][j][i] + a[k+1][j][i]) + (a[k][j-1][i] + a[k][j+1][i]))
;
}
}
}
``

**Comment by cod3monk** [comment]
@sguera Did this resolve your problem?

**Comment by sguera** [comment]
I am not sure. I tried again and I got the following:
```
kerncraft -p LC cazzo.c -m HaswellEX_E5-2695v3.yml -D M 250 -D N 250 -D P 250
Traceback (most recent call last):
  File "/Applications/anaconda/bin/kerncraft", line 11, in <module>
    load_entry_point('kerncraft==0.5.9', 'console_scripts', 'kerncraft')()
  File "/Applications/anaconda/lib/python2.7/site-packages/kerncraft/kerncraft.py", line 294, in main
    run(parser, args)
  File "/Applications/anaconda/lib/python2.7/site-packages/kerncraft/kerncraft.py", line 201, in run
    kernel = KernelCode(code, filename=args.code_file.name, machine=machine)
  File "/Applications/anaconda/lib/python2.7/site-packages/kerncraft/kernel.py", line 593, in __init__
    yacctab='kerncraft.pycparser.yacctab')
  File "/Applications/anaconda/lib/python2.7/site-packages/kerncraft/pycparser/c_parser.py", line 88, in __init__
    outputdir=taboutputdir)
  File "/Applications/anaconda/lib/python2.7/site-packages/kerncraft/pycparser/c_lexer.py", line 66, in build
    self.lexer = lex.lex(object=self, **kwargs)
  File "/Applications/anaconda/lib/python2.7/site-packages/kerncraft/pycparser/ply/lex.py", line 914, in lex
    lexobj.readtab(lextab, ldict)
  File "/Applications/anaconda/lib/python2.7/site-packages/kerncraft/pycparser/ply/lex.py", line 233, in readtab
    titem.append((re.compile(pat, lextab._lexreflags), _names_to_funcs(func_name, fdict)))
  File "/Applications/anaconda/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/Applications/anaconda/lib/python2.7/re.py", line 249, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Applications/anaconda/lib/python2.7/sre_compile.py", line 583, in compile
    "sorry, but this version only supports 100 named groups"
AssertionError: sorry, but this version only supports 100 named groups
```
So I am not sure it gets through. I tried a fresh installation of kerncraft.

**Comment by sguera** [comment]
In a python 3.5 environment it failsto build kerncraft
```
Building wheels for collected packages: kerncraft, ruamel.yaml, sympy, pycachesim, pylru, mpmath
  Running setup.py bdist_wheel for kerncraft ... error
  Complete output from command /Applications/anaconda/envs/myenv3.5/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/j8/mvrmj1y96bj6949183ylcgcr001jgw/T/pip-build-mxkx8erv/kerncraft/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/j8/mvrmj1y96bj6949183ylcgcr001jgw/T/tmp3zzagm05pip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  Build the lexing/parsing tables
  Traceback (most recent call last):
    File "_build_tables.py", line 15, in <module>
      ast_gen = ASTCodeGenerator('_c_ast.cfg')
    File "/private/var/folders/j8/mvrmj1y96bj6949183ylcgcr001jgw/T/pip-build-mxkx8erv/kerncraft/kerncraft/pycparser/_ast_gen.py", line 24, in __init__
      for (name, contents) in self.parse_cfgfile(cfg_filename)]
    File "/private/var/folders/j8/mvrmj1y96bj6949183ylcgcr001jgw/T/pip-build-mxkx8erv/kerncraft/kerncraft/pycparser/_ast_gen.py", line 23, in <listcomp>
      self.node_cfg = [NodeCfg(name, contents)
    File "/private/var/folders/j8/mvrmj1y96bj6949183ylcgcr001jgw/T/pip-build-mxkx8erv/kerncraft/kerncraft/pycparser/_ast_gen.py", line 42, in parse_cfgfile
      with open(filename, "r") as f:
  FileNotFoundError: [Errno 2] No such file or directory: '_c_ast.cfg'
  creating build
  creating build/lib
  creating build/lib/kerncraft

...

Copying kerncraft.egg-info to build/bdist.macosx-10.7-x86_64/wheel/kerncraft-0.5.9-py3.5.egg-info
  running install_scripts
  error: [Errno 2] No such file or directory: 'LICENSE'
  
  ----------------------------------------
  Failed building wheel for kerncraft
  Running setup.py clean for kerncraft
  Running setup.py bdist_wheel for ruamel.yaml ... done
  Stored in directory: /Users/guerrera/Library/Caches/pip/wheels/78/13/d6/9b33af117c67cb0cfb64a08d27d5edbf6c52148536e1088032
  Running setup.py bdist_wheel for sympy ... done
  Stored in directory: /Users/guerrera/Library/Caches/pip/wheels/86/b6/ef/72760cc52418901e59f20a85454243f2c9503a8f89b5501f5f
  Running setup.py bdist_wheel for pycachesim ... done
  Stored in directory: /Users/guerrera/Library/Caches/pip/wheels/13/1b/01/cb59a3e9e0f23fa175799d70681519a1804f80be2676f832e8
  Running setup.py bdist_wheel for pylru ... done
  Stored in directory: /Users/guerrera/Library/Caches/pip/wheels/6b/c5/19/6ffd2f199a590dffc62488601d2a1e5799a8e789ace46cc5ac
  Running setup.py bdist_wheel for mpmath ... done
  Stored in directory: /Users/guerrera/Library/Caches/pip/wheels/f9/86/f7/eecdbbecc0bc292faa3dfbafd546c38b73ae9762aee9e9ac82
Successfully built ruamel.yaml sympy pycachesim pylru mpmath
Failed to build kerncraft
Installing collected packages: ruamel.yaml, six, mpmath, sympy, pycachesim, pylru, numpy, idna, certifi, urllib3, chardet, requests, kerncraft
  Found existing installation: certifi 2016.2.28
    Uninstalling certifi-2016.2.28:
      Successfully uninstalled certifi-2016.2.28
  Running setup.py install for kerncraft ... done
Successfully installed certifi-2017.11.5 chardet-3.0.4 idna-2.6 kerncraft-0.5.9 mpmath-1.0.0 numpy-1.13.3 pycachesim-0.1.5 pylru-1.0.9 requests-2.18.4 ruamel.yaml-0.13.14 six-1.11.0 sympy-1.1.1 urllib3-1.22
```

even ith the error there, I can:
```
kerncraft -p LC code.c -m HaswellEX_E5-2695v3.yml -D M 200 -D N 200
================================== kerncraft ===================================
code.c                                               -m HaswellEX_E5-2695v3.yml
-D N 200 -D M 200
-------------------------------------- LC --------------------------------------
1D Layer-Condition:
L1: unconditionally fulfilled
L2: unconditionally fulfilled
L3: unconditionally fulfilled
2D Layer-Condition:
L1: N <= 2048/3
L2: N <= 16384/3
L3: N <= 2293760/3
```

**Comment by cod3monk** [comment]
It looks like your checkout is incomplete, it complains about a missing LICENSE file, which is available in the repository.

The previous error might be caused by an older version of the pycparser, which should have been resolved. I am also planing drop support for python  <3.4 or <3.5 in the future, which will ultimately resolve that issue.

**Comment by sguera** [comment]
Coming back to this:

using pip I get the error:

```
pip install kerncraft
Collecting kerncraft
  Downloading kerncraft-0.5.10.tar.gz (189kB)
    100% |████████████████████████████████| 194kB 1.5MB/s 
Collecting ruamel.yaml<0.14.0,>=0.13.4 (from kerncraft)
  Using cached ruamel.yaml-0.13.14-cp27-cp27mu-manylinux1_x86_64.whl
Collecting six (from kerncraft)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting sympy>=0.7.7 (from kerncraft)
Collecting pycachesim>=0.1.5 (from kerncraft)
Collecting pylru (from kerncraft)
Collecting numpy (from kerncraft)
  Using cached numpy-1.13.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting requests (from kerncraft)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting ruamel.ordereddict (from ruamel.yaml<0.14.0,>=0.13.4->kerncraft)
  Using cached ruamel.ordereddict-0.4.13-cp27-cp27mu-manylinux1_x86_64.whl
Collecting typing (from ruamel.yaml<0.14.0,>=0.13.4->kerncraft)
  Using cached typing-3.6.2-py2-none-any.whl
Collecting mpmath>=0.19 (from sympy>=0.7.7->kerncraft)
Collecting urllib3<1.23,>=1.21.1 (from requests->kerncraft)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests->kerncraft)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->kerncraft)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->kerncraft)
  Downloading certifi-2017.11.5-py2.py3-none-any.whl (330kB)
    100% |████████████████████████████████| 337kB 1.0MB/s 
Building wheels for collected packages: kerncraft
  Running setup.py bdist_wheel for kerncraft ... error
  Complete output from command /users/staff/ifi/guerrera/anaconda2/envs/myenv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hA1hbo/kerncraft/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpK5yDlrpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  Build the lexing/parsing tables
  Traceback (most recent call last):
    File "_build_tables.py", line 15, in <module>
      ast_gen = ASTCodeGenerator('_c_ast.cfg')
    File "/tmp/pip-build-hA1hbo/kerncraft/kerncraft/pycparser/_ast_gen.py", line 24, in __init__
      for (name, contents) in self.parse_cfgfile(cfg_filename)]
    File "/tmp/pip-build-hA1hbo/kerncraft/kerncraft/pycparser/_ast_gen.py", line 42, in parse_cfgfile
      with open(filename, "r") as f:
  IOError: [Errno 2] No such file or directory: '_c_ast.cfg'
  creating build
  creating build/lib
  creating build/lib/kerncraft
  copying kerncraft/roofline-plot.py -> build/lib/kerncraft
  copying kerncraft/prefixedunit.py -> build/lib/kerncraft
  copying kerncraft/picklemerge.py -> build/lib/kerncraft
  copying kerncraft/machinemodel.py -> build/lib/kerncraft
  copying kerncraft/likwid_bench_auto.py -> build/lib/kerncraft
  copying kerncraft/kernel.py -> build/lib/kerncraft
  copying kerncraft/kerncraft.py -> build/lib/kerncraft
  copying kerncraft/intervals.py -> build/lib/kerncraft
  copying kerncraft/iaca_get.py -> build/lib/kerncraft
  copying kerncraft/iaca.py -> build/lib/kerncraft
  copying kerncraft/cachetile.py -> build/lib/kerncraft
  copying kerncraft/cacheprediction.py -> build/lib/kerncraft
  copying kerncraft/__init__.py -> build/lib/kerncraft
  creating build/lib/kerncraft/pycparser
  copying kerncraft/pycparser/lextab.py -> build/lib/kerncraft/pycparser
  copying kerncraft/pycparser/yacctab.py -> build/lib/kerncraft/pycparser
  copying kerncraft/pycparser/plyparser.py -> build/lib/kerncraft/pycparser
  copying kerncraft/pycparser/c_parser.py -> build/lib/kerncraft/pycparser
  copying kerncraft/pycparser/c_lexer.py -> build/lib/kerncraft/pycparser
  copying kerncraft/pycparser/c_generator.py -> build/lib/kerncraft/pycparser
  copying kerncraft/pycparser/c_ast.py -> build/lib/kerncraft/pycparser
  copying kerncraft/pycparser/ast_transforms.py -> build/lib/kerncraft/pycparser
  copying kerncraft/pycparser/_build_tables.py -> build/lib/kerncraft/pycparser
  copying kerncraft/pycparser/_ast_gen.py -> build/lib/kerncraft/pycparser
  copying kerncraft/pycparser/__init__.py -> build/lib/kerncraft/pycparser
  creating build/lib/kerncraft/models
  copying kerncraft/models/roofline.py -> build/lib/kerncraft/models
  copying kerncraft/models/layer_condition.py -> build/lib/kerncraft/models
  copying kerncraft/models/ecm.py -> build/lib/kerncraft/models
  copying kerncraft/models/benchmark.py -> build/lib/kerncraft/models
  copying kerncraft/models/__init__.py -> build/lib/kerncraft/models
  creating build/lib/kerncraft/pycparser/ply
  copying kerncraft/pycparser/ply/ygen.py -> build/lib/kerncraft/pycparser/ply
  copying kerncraft/pycparser/ply/yacc.py -> build/lib/kerncraft/pycparser/ply
  copying kerncraft/pycparser/ply/lex.py -> build/lib/kerncraft/pycparser/ply
  copying kerncraft/pycparser/ply/ctokens.py -> build/lib/kerncraft/pycparser/ply
  copying kerncraft/pycparser/ply/cpp.py -> build/lib/kerncraft/pycparser/ply
  copying kerncraft/pycparser/ply/__init__.py -> build/lib/kerncraft/pycparser/ply
  running egg_info
  writing requirements to kerncraft.egg-info/requires.txt
  writing kerncraft.egg-info/PKG-INFO
  writing top-level names to kerncraft.egg-info/top_level.txt
  writing dependency_links to kerncraft.egg-info/dependency_links.txt
  writing entry points to kerncraft.egg-info/entry_points.txt
  reading manifest file 'kerncraft.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'examples/kernels/*.c_compilable.c'
  writing manifest file 'kerncraft.egg-info/SOURCES.txt'
  creating build/lib/kerncraft/headers
  copying kerncraft/headers/dummy.c -> build/lib/kerncraft/headers
  copying kerncraft/headers/kerncraft.h -> build/lib/kerncraft/headers
  copying kerncraft/headers/timing.c -> build/lib/kerncraft/headers
  copying kerncraft/headers/timing.h -> build/lib/kerncraft/headers
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/kerncraft
  creating build/bdist.linux-x86_64/wheel/kerncraft/headers
  copying build/lib/kerncraft/headers/timing.h -> build/bdist.linux-x86_64/wheel/kerncraft/headers
  copying build/lib/kerncraft/headers/timing.c -> build/bdist.linux-x86_64/wheel/kerncraft/headers
  copying build/lib/kerncraft/headers/kerncraft.h -> build/bdist.linux-x86_64/wheel/kerncraft/headers
  copying build/lib/kerncraft/headers/dummy.c -> build/bdist.linux-x86_64/wheel/kerncraft/headers
  creating build/bdist.linux-x86_64/wheel/kerncraft/models
  copying build/lib/kerncraft/models/__init__.py -> build/bdist.linux-x86_64/wheel/kerncraft/models
  copying build/lib/kerncraft/models/benchmark.py -> build/bdist.linux-x86_64/wheel/kerncraft/models
  copying build/lib/kerncraft/models/ecm.py -> build/bdist.linux-x86_64/wheel/kerncraft/models
  copying build/lib/kerncraft/models/layer_condition.py -> build/bdist.linux-x86_64/wheel/kerncraft/models
  copying build/lib/kerncraft/models/roofline.py -> build/bdist.linux-x86_64/wheel/kerncraft/models
  creating build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  creating build/bdist.linux-x86_64/wheel/kerncraft/pycparser/ply
  copying build/lib/kerncraft/pycparser/ply/__init__.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser/ply
  copying build/lib/kerncraft/pycparser/ply/cpp.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser/ply
  copying build/lib/kerncraft/pycparser/ply/ctokens.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser/ply
  copying build/lib/kerncraft/pycparser/ply/lex.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser/ply
  copying build/lib/kerncraft/pycparser/ply/yacc.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser/ply
  copying build/lib/kerncraft/pycparser/ply/ygen.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser/ply
  copying build/lib/kerncraft/pycparser/__init__.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  copying build/lib/kerncraft/pycparser/_ast_gen.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  copying build/lib/kerncraft/pycparser/_build_tables.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  copying build/lib/kerncraft/pycparser/ast_transforms.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  copying build/lib/kerncraft/pycparser/c_ast.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  copying build/lib/kerncraft/pycparser/c_generator.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  copying build/lib/kerncraft/pycparser/c_lexer.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  copying build/lib/kerncraft/pycparser/c_parser.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  copying build/lib/kerncraft/pycparser/plyparser.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  copying build/lib/kerncraft/pycparser/yacctab.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  copying build/lib/kerncraft/pycparser/lextab.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  copying build/lib/kerncraft/__init__.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/cacheprediction.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/cachetile.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/iaca.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/iaca_get.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/intervals.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/kerncraft.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/kernel.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/likwid_bench_auto.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/machinemodel.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/picklemerge.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/prefixedunit.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/roofline-plot.py -> build/bdist.linux-x86_64/wheel/kerncraft
  running install_egg_info
  Copying kerncraft.egg-info to build/bdist.linux-x86_64/wheel/kerncraft-0.5.10-py2.7.egg-info
  running install_scripts
  error: [Errno 2] No such file or directory: 'LICENSE'
  
  ----------------------------------------
  Failed building wheel for kerncraft
  Running setup.py clean for kerncraft
Failed to build kerncraft

```

**Comment by sguera** [comment]
Let's continue the installation problem here: https://github.com/RRZE-HPC/kerncraft/issues/65
