### ISSUE TITLE
Error while installing via pip

### ISSUE THREAD

**Issue by sguera** [RRZE-HPC/kerncraft#65]
When trying to install it via pip:

```
pip install kerncraft
Collecting kerncraft
  Downloading kerncraft-0.5.10.tar.gz (189kB)
    100% |████████████████████████████████| 194kB 1.5MB/s 
Collecting ruamel.yaml<0.14.0,>=0.13.4 (from kerncraft)
  Using cached ruamel.yaml-0.13.14-cp27-cp27mu-manylinux1_x86_64.whl
Collecting six (from kerncraft)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting sympy>=0.7.7 (from kerncraft)
Collecting pycachesim>=0.1.5 (from kerncraft)
Collecting pylru (from kerncraft)
Collecting numpy (from kerncraft)
  Using cached numpy-1.13.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting requests (from kerncraft)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting ruamel.ordereddict (from ruamel.yaml<0.14.0,>=0.13.4->kerncraft)
  Using cached ruamel.ordereddict-0.4.13-cp27-cp27mu-manylinux1_x86_64.whl
Collecting typing (from ruamel.yaml<0.14.0,>=0.13.4->kerncraft)
  Using cached typing-3.6.2-py2-none-any.whl
Collecting mpmath>=0.19 (from sympy>=0.7.7->kerncraft)
Collecting urllib3<1.23,>=1.21.1 (from requests->kerncraft)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests->kerncraft)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->kerncraft)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->kerncraft)
  Downloading certifi-2017.11.5-py2.py3-none-any.whl (330kB)
    100% |████████████████████████████████| 337kB 1.0MB/s 
Building wheels for collected packages: kerncraft
  Running setup.py bdist_wheel for kerncraft ... error
  Complete output from command /users/staff/ifi/guerrera/anaconda2/envs/myenv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hA1hbo/kerncraft/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpK5yDlrpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  Build the lexing/parsing tables
  Traceback (most recent call last):
    File "_build_tables.py", line 15, in <module>
      ast_gen = ASTCodeGenerator('_c_ast.cfg')
    File "/tmp/pip-build-hA1hbo/kerncraft/kerncraft/pycparser/_ast_gen.py", line 24, in __init__
      for (name, contents) in self.parse_cfgfile(cfg_filename)]
    File "/tmp/pip-build-hA1hbo/kerncraft/kerncraft/pycparser/_ast_gen.py", line 42, in parse_cfgfile
      with open(filename, "r") as f:
  IOError: [Errno 2] No such file or directory: '_c_ast.cfg'
  creating build
  creating build/lib
  creating build/lib/kerncraft
  copying kerncraft/roofline-plot.py -> build/lib/kerncraft
  copying kerncraft/prefixedunit.py -> build/lib/kerncraft
  copying kerncraft/picklemerge.py -> build/lib/kerncraft
  copying kerncraft/machinemodel.py -> build/lib/kerncraft
  copying kerncraft/likwid_bench_auto.py -> build/lib/kerncraft
  copying kerncraft/kernel.py -> build/lib/kerncraft
  copying kerncraft/kerncraft.py -> build/lib/kerncraft
  copying kerncraft/intervals.py -> build/lib/kerncraft
  copying kerncraft/iaca_get.py -> build/lib/kerncraft
  copying kerncraft/iaca.py -> build/lib/kerncraft
  copying kerncraft/cachetile.py -> build/lib/kerncraft
  copying kerncraft/cacheprediction.py -> build/lib/kerncraft
  copying kerncraft/__init__.py -> build/lib/kerncraft
  creating build/lib/kerncraft/pycparser
  copying kerncraft/pycparser/lextab.py -> build/lib/kerncraft/pycparser
  copying kerncraft/pycparser/yacctab.py -> build/lib/kerncraft/pycparser
  copying kerncraft/pycparser/plyparser.py -> build/lib/kerncraft/pycparser
  copying kerncraft/pycparser/c_parser.py -> build/lib/kerncraft/pycparser
  copying kerncraft/pycparser/c_lexer.py -> build/lib/kerncraft/pycparser
  copying kerncraft/pycparser/c_generator.py -> build/lib/kerncraft/pycparser
  copying kerncraft/pycparser/c_ast.py -> build/lib/kerncraft/pycparser
  copying kerncraft/pycparser/ast_transforms.py -> build/lib/kerncraft/pycparser
  copying kerncraft/pycparser/_build_tables.py -> build/lib/kerncraft/pycparser
  copying kerncraft/pycparser/_ast_gen.py -> build/lib/kerncraft/pycparser
  copying kerncraft/pycparser/__init__.py -> build/lib/kerncraft/pycparser
  creating build/lib/kerncraft/models
  copying kerncraft/models/roofline.py -> build/lib/kerncraft/models
  copying kerncraft/models/layer_condition.py -> build/lib/kerncraft/models
  copying kerncraft/models/ecm.py -> build/lib/kerncraft/models
  copying kerncraft/models/benchmark.py -> build/lib/kerncraft/models
  copying kerncraft/models/__init__.py -> build/lib/kerncraft/models
  creating build/lib/kerncraft/pycparser/ply
  copying kerncraft/pycparser/ply/ygen.py -> build/lib/kerncraft/pycparser/ply
  copying kerncraft/pycparser/ply/yacc.py -> build/lib/kerncraft/pycparser/ply
  copying kerncraft/pycparser/ply/lex.py -> build/lib/kerncraft/pycparser/ply
  copying kerncraft/pycparser/ply/ctokens.py -> build/lib/kerncraft/pycparser/ply
  copying kerncraft/pycparser/ply/cpp.py -> build/lib/kerncraft/pycparser/ply
  copying kerncraft/pycparser/ply/__init__.py -> build/lib/kerncraft/pycparser/ply
  running egg_info
  writing requirements to kerncraft.egg-info/requires.txt
  writing kerncraft.egg-info/PKG-INFO
  writing top-level names to kerncraft.egg-info/top_level.txt
  writing dependency_links to kerncraft.egg-info/dependency_links.txt
  writing entry points to kerncraft.egg-info/entry_points.txt
  reading manifest file 'kerncraft.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'examples/kernels/*.c_compilable.c'
  writing manifest file 'kerncraft.egg-info/SOURCES.txt'
  creating build/lib/kerncraft/headers
  copying kerncraft/headers/dummy.c -> build/lib/kerncraft/headers
  copying kerncraft/headers/kerncraft.h -> build/lib/kerncraft/headers
  copying kerncraft/headers/timing.c -> build/lib/kerncraft/headers
  copying kerncraft/headers/timing.h -> build/lib/kerncraft/headers
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/kerncraft
  creating build/bdist.linux-x86_64/wheel/kerncraft/headers
  copying build/lib/kerncraft/headers/timing.h -> build/bdist.linux-x86_64/wheel/kerncraft/headers
  copying build/lib/kerncraft/headers/timing.c -> build/bdist.linux-x86_64/wheel/kerncraft/headers
  copying build/lib/kerncraft/headers/kerncraft.h -> build/bdist.linux-x86_64/wheel/kerncraft/headers
  copying build/lib/kerncraft/headers/dummy.c -> build/bdist.linux-x86_64/wheel/kerncraft/headers
  creating build/bdist.linux-x86_64/wheel/kerncraft/models
  copying build/lib/kerncraft/models/__init__.py -> build/bdist.linux-x86_64/wheel/kerncraft/models
  copying build/lib/kerncraft/models/benchmark.py -> build/bdist.linux-x86_64/wheel/kerncraft/models
  copying build/lib/kerncraft/models/ecm.py -> build/bdist.linux-x86_64/wheel/kerncraft/models
  copying build/lib/kerncraft/models/layer_condition.py -> build/bdist.linux-x86_64/wheel/kerncraft/models
  copying build/lib/kerncraft/models/roofline.py -> build/bdist.linux-x86_64/wheel/kerncraft/models
  creating build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  creating build/bdist.linux-x86_64/wheel/kerncraft/pycparser/ply
  copying build/lib/kerncraft/pycparser/ply/__init__.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser/ply
  copying build/lib/kerncraft/pycparser/ply/cpp.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser/ply
  copying build/lib/kerncraft/pycparser/ply/ctokens.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser/ply
  copying build/lib/kerncraft/pycparser/ply/lex.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser/ply
  copying build/lib/kerncraft/pycparser/ply/yacc.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser/ply
  copying build/lib/kerncraft/pycparser/ply/ygen.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser/ply
  copying build/lib/kerncraft/pycparser/__init__.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  copying build/lib/kerncraft/pycparser/_ast_gen.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  copying build/lib/kerncraft/pycparser/_build_tables.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  copying build/lib/kerncraft/pycparser/ast_transforms.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  copying build/lib/kerncraft/pycparser/c_ast.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  copying build/lib/kerncraft/pycparser/c_generator.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  copying build/lib/kerncraft/pycparser/c_lexer.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  copying build/lib/kerncraft/pycparser/c_parser.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  copying build/lib/kerncraft/pycparser/plyparser.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  copying build/lib/kerncraft/pycparser/yacctab.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  copying build/lib/kerncraft/pycparser/lextab.py -> build/bdist.linux-x86_64/wheel/kerncraft/pycparser
  copying build/lib/kerncraft/__init__.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/cacheprediction.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/cachetile.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/iaca.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/iaca_get.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/intervals.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/kerncraft.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/kernel.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/likwid_bench_auto.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/machinemodel.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/picklemerge.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/prefixedunit.py -> build/bdist.linux-x86_64/wheel/kerncraft
  copying build/lib/kerncraft/roofline-plot.py -> build/bdist.linux-x86_64/wheel/kerncraft
  running install_egg_info
  Copying kerncraft.egg-info to build/bdist.linux-x86_64/wheel/kerncraft-0.5.10-py2.7.egg-info
  running install_scripts
  error: [Errno 2] No such file or directory: 'LICENSE'
  
  ----------------------------------------
  Failed building wheel for kerncraft
  Running setup.py clean for kerncraft
Failed to build kerncraft

```

**Comment by cod3monk** [comment]
Can you verify?

**Comment by sguera** [comment]
Tried right now, still getting it

**Comment by cod3monk** [comment]
DId you try the pip install from pypi or from the github repo?

**Comment by sguera** [comment]
From pypi

**Comment by cod3monk** [comment]
You will need to install it from github, since I did not release a new version to pypi yet (next will be 0.6.0, with dropped py2.7 support - but I'm still waiting on a few more issues to be resolved)

**Comment by cod3monk** [comment]
`pip install git+https://github.com/RRZE-HPC/kerncraft.git`

**Comment by sguera** [comment]
ok thanks
