### ISSUE TITLE
roofline is not limited to Flops

### ISSUE THREAD

**Issue by psteinb** [RRZE-HPC/kerncraft#85]
just got this with 83f46fb200e5fe0669f54a2e0287d12d935c78fa:

```
$ kerncraft --unit "It/s" -p Roofline -m /home/steinbac/software/kerncraft/repo/examples/machine-files/IvyBridgeEP_E5-2660v2.yml /home/steinbac/software/kerncraft/repo/examples/kernels/copy.c -D N 1000  
                                   kerncraft                                    
/home/steinbac/software/kerncraft/repo/examples/kernels/copy.c-m /home/steinbac/software/kerncraft/repo/examples/machine-files/IvyBridgeEP_E5-2660v2.yml
-D N 1000
----------------------------------- Roofline -----------------------------------
Traceback (most recent call last):
  File "/home/steinbac/software/kerncraft/master/bin/kerncraft", line 11, in <module>
    load_entry_point('kerncraft==0.6.3', 'console_scripts', 'kerncraft')()
  File "/home/steinbac/software/kerncraft/master/lib/python3.6/site-packages/kerncraft-0.6.3-py3.6.egg/kerncraft/kerncraft.py", line 284, in main
    run(parser, args)
  File "/home/steinbac/software/kerncraft/master/lib/python3.6/site-packages/kerncraft-0.6.3-py3.6.egg/kerncraft/kerncraft.py", line 248, in run
    model = getattr(models, model_name)(kernel, machine, args, parser)
  File "/home/steinbac/software/kerncraft/master/lib/python3.6/site-packages/kerncraft-0.6.3-py3.6.egg/kerncraft/models/roofline.py", line 59, in __init__
    raise ValueError("The Roofline model requires that the sum of FLOPs is non-zero.")
ValueError: The Roofline model requires that the sum of FLOPs is non-zero.
```
even though I told kerncraft not to use FLOPs as a metric. :(

**Comment by cod3monk** [comment]
The internal calculation of the Roofline model is always based on FLOPs. A different model, which is a bit more complex but in many cases more accurate, is the ECM model. The ECM model is based on cy/CL (cycles per cache-line work).
