### ISSUE TITLE
TypeError when running ECM model

### ISSUE THREAD

**Issue by sguera** [RRZE-HPC/kerncraft#88]
While running the following command:
```
kerncraft  -p ECM 2d-2r-isotropic-constant-star-stencil.c -m Intel_Xeon_CPU_E5-2640_v4_mod.yml -D M 1767 -D N 1767 -v
```
I get:
```
kerncraft                                    
2d-2r-isotropic-constant-star-stencil.c-m Intel_Xeon_CPU_E5-2640_v4_mod.yml
-D N 1767 -D M 1767
------------------------------------- ECM --------------------------------------
constants:     name | value     
           ---------+-----------
                  M | 1767      
                  N | 1767      
           

Traceback (most recent call last):
  File "/users/staff/ifi/guerrera/anaconda2/envs/myenv/bin/kerncraft", line 11, in <module>
    load_entry_point('kerncraft==0.6.4', 'console_scripts', 'kerncraft')()
  File "/users/staff/ifi/guerrera/anaconda2/envs/myenv/lib/python3.5/site-packages/kerncraft/kerncraft.py", line 284, in main
    run(parser, args)
  File "/users/staff/ifi/guerrera/anaconda2/envs/myenv/lib/python3.5/site-packages/kerncraft/kerncraft.py", line 250, in run
    model.analyze()
  File "/users/staff/ifi/guerrera/anaconda2/envs/myenv/lib/python3.5/site-packages/kerncraft/models/ecm.py", line 397, in analyze
    self._data.analyze()
  File "/users/staff/ifi/guerrera/anaconda2/envs/myenv/lib/python3.5/site-packages/kerncraft/models/ecm.py", line 157, in analyze
    self.calculate_cycles()
  File "/users/staff/ifi/guerrera/anaconda2/envs/myenv/lib/python3.5/site-packages/kerncraft/models/ecm.py", line 126, in calculate_cycles
    cache_level + 1, read_streams, write_streams, threads_per_core)
  File "/users/staff/ifi/guerrera/anaconda2/envs/myenv/lib/python3.5/site-packages/kerncraft/machinemodel.py", line 113, in get_bandwidth
    bw = max(bw_measurements['results'][measurement_kernel][:max_cores])
TypeError: slice indices must be integers or None or have an __index__ method
```
[Intel_Xeon_CPU_E5-2640_v4_mod.yml.txt](https://github.com/RRZE-HPC/kerncraft/files/1635537/Intel_Xeon_CPU_E5-2640_v4_mod.yml.txt)

[2d-2r-isotropic-constant-star-stencil.c.txt](https://github.com/RRZE-HPC/kerncraft/files/1635331/2d-2r-isotropic-constant-star-stencil.c.txt)

**Comment by sguera** [comment]
Found the error, due to a wrong

```
cores per NUMA domain: 0.1
```

Changed it to the correct value of 10 and it went through
