### ISSUE TITLE
Benchmark run fails with himeno.c

### ISSUE THREAD

**Issue by rrzeschorscherl** [RRZE-HPC/kerncraft#90]
version 0.6.4
Haswell-EP 8hasep1@rrze)

```
$ kerncraft --machine machine-files/hasep1_CoD.yml  --compiler icc --cache-predictor LC -D L 1025 -D M 513 -D N 513 --pmodel Benchmark -vvv kernels/himeno.c
[... output looks good so far ...]
WARNING: current CPU frequency and machine description do not match. (2300000000.0 vs None)
Executing (build):  icc /home/hpc/unrz/unrz55/programming/py/venv/lib/python3.5/site-packages/kerncraft/headers/dummy.c kernels/himeno.c_compilable.c -Ofast -xCORE-AVX2 -fno-alias -std=c99 -I/home/hpc/unrz/unrz55/programming/py/venv/lib/python3.5/site-packages/kerncraft/headers/ -I/mnt/opt/likwid-4.3.1/include -llikwid -L/mnt/opt/likwid-4.3.1/lib -pthread -o /home/hpc/unrz/unrz55/programming/py/kerncraft/examples/kernels/himeno.likwid_marked
likwid-perfctr -f -O -g MEM -C S0:0 -m /home/hpc/unrz/unrz55/programming/py/kerncraft/examples/kernels/himeno.likwid_marked 513 1025 513 100
likwid-perfctr -f -O -g LLC_LOOKUP_DATA_READ:CBOX3C1,LLC_VICTIMS_M:CBOX11C0,LLC_VICTIMS_M:CBOX4C0,LLC_VICTIMS_M:CBOX8C1,LLC_VICTIMS_M:CBOX7C0,LLC_LOOKUP_DATA_READ:CBOX5C1,LLC_VICTIMS_M:CBOX3C0,LLC_VICTIMS_M:CBOX9C1,LLC_LOOKUP_DATA_READ:CBOX8C0,L1D_REPLACEMENT:PMC0,LLC_LOOKUP_DATA_READ:CBOX1C0,LLC_VICTIMS_M:CBOX0C1,LLC_VICTIMS_M:CBOX12C0,LLC_LOOKUP_DATA_READ:CBOX16C0,LLC_VICTIMS_M:CBOX2C1,LLC_LOOKUP_DATA_READ:CBOX10C0,LLC_LOOKUP_DATA_READ:CBOX2C0,LLC_VICTIMS_M:CBOX5C0,LLC_LOOKUP_DATA_READ:CBOX15C0,LLC_VICTIMS_M:CBOX1C1,UOPS_EXECUTED_PORT_PORT_4:PMC1,LLC_LOOKUP_DATA_READ:CBOX17C0,LLC_LOOKUP_DATA_READ:CBOX11C1,LLC_LOOKUP_DATA_READ:CBOX14C0,LLC_VICTIMS_M:CBOX10C1,LLC_LOOKUP_DATA_READ:CBOX13C1,LLC_LOOKUP_DATA_READ:CBOX7C1,LLC_LOOKUP_DATA_READ:CBOX0C0,LLC_LOOKUP_DATA_READ:CBOX12C1,LLC_VICTIMS_M:CBOX6C1,UOPS_EXECUTED_PORT_PORT_1:PMC2,LLC_LOOKUP_DATA_READ:CBOX6C0,LLC_LOOKUP_DATA_READ:CBOX4C1,L2_TRANS_L2_WB:PMC3,LLC_VICTIMS_M:CBOX13C0,LLC_LOOKUP_DATA_READ:CBOX9C0 -C S0:0 -m /home/hpc/unrz/unrz55/programming/py/kerncraft/examples/kernels/himeno.likwid_marked 513 1025 513 100
likwid-perfctr -f -O -g UOPS_EXECUTED_PORT_PORT_7:PMC3,UOPS_EXECUTED_PORT_PORT_6:PMC0,UOPS_EXECUTED_PORT_PORT_0:PMC2,MEM_UOPS_RETIRED_LOADS:PMC1 -C S0:0 -m /home/hpc/unrz/unrz55/programming/py/kerncraft/examples/kernels/himeno.likwid_marked 513 1025 513 100
likwid-perfctr -f -O -g L1D_M_EVICT:PMC0,L2_LINES_IN_ALL:PMC2,UOPS_EXECUTED_PORT_PORT_5:PMC1 -C S0:0 -m /home/hpc/unrz/unrz55/programming/py/kerncraft/examples/kernels/himeno.likwid_marked 513 1025 513 100
Traceback (most recent call last):
  File "/home/hpc/unrz/unrz55/programming/py/venv/bin/kerncraft", line 11, in <module>
    sys.exit(main())
  File "/home/hpc/unrz/unrz55/programming/py/venv/lib/python3.5/site-packages/kerncraft/kerncraft.py", line 284, in main
    run(parser, args)
  File "/home/hpc/unrz/unrz55/programming/py/venv/lib/python3.5/site-packages/kerncraft/kerncraft.py", line 250, in run
    model.analyze()
  File "/home/hpc/unrz/unrz55/programming/py/venv/lib/python3.5/site-packages/kerncraft/models/benchmark.py", line 335, in analyze
    for cache, d in cache_metric_results.items()}
  File "/home/hpc/unrz/unrz55/programming/py/venv/lib/python3.5/site-packages/kerncraft/models/benchmark.py", line 335, in <dictcomp>
    for cache, d in cache_metric_results.items()}
  File "/home/hpc/unrz/unrz55/programming/py/venv/lib/python3.5/site-packages/kerncraft/models/benchmark.py", line 334, in <dictcomp>
    for k, v in d.items()}
  File "/home/hpc/unrz/unrz55/programming/py/venv/lib/python3.5/site-packages/kerncraft/prefixedunit.py", line 42, in __init__
    args = [float(args[0]), gd['prefix'], gd['unit']]
  File "/home/hpc/unrz/unrz55/programming/py/venv/lib/python3.5/site-packages/sympy/core/expr.py", line 239, in __float__
    raise TypeError("can't convert expression to float")
TypeError: can't convert expression to float
```

**Comment by cod3monk** [comment]
Have you tried it with the latests version of the machine file? The format changed slightly during the last months.

https://github.com/RRZE-HPC/kerncraft/blob/master/examples/machine-files/HaswellEX_E5-2695v3_CoD.yml

**Comment by rrzeschorscherl** [comment]
I had done a git pull just before the run, and my machine file is a 1:1 copy of the Haswell*CoD.yml

**Comment by cod3monk** [comment]
I will need to run this on hasep1, since I am unable to reproduce on any other machines. It could also be related the likwid verison in use. Which one do you use?

**Comment by rrzeschorscherl** [comment]
I am using likwid 4.3.1 (default module on hasep1).

The node is now available for benchmarking.
