### ISSUE TITLE
# of iterations in Benchmark mode should be adaptive or configurable

### ISSUE THREAD

**Issue by rrzeschorscherl** [RRZE-HPC/kerncraft#91]
In 0.6.4, 100 iterations are done on Benchmark mode independent of problem kind and size. This can lead to very (too) short or very (too) long execution times. My suggestion is to have a default for the runtime of the measurement that makes sure that the benchmark runs for at least, say, 5 seconds. In addition, the user could specify either the number of iterations or the minimum runtime as a command-line parameter.

**Comment by cod3monk** [comment]
Use `--iterations` in benchmark mode to adapt minimum. Minimum is now set to 10 by default.

**Comment by rrzeschorscherl** [comment]
Specifying the iterations manually works now, but if I don't say anything then:

```
$ kerncraft --machine machine-files/hasep1_CoD.yml  --compiler icc --cache-predictor LC -D L 257 -D M 129 -D N 129 --pmodel Benchmark --unit FLOP/s  -vvv kernels/himeno.c
[...]
Executing (build):  icc /home/hpc/unrz/unrz55/programming/py/venv/lib/python3.5/site-packages/kerncraft-0.6.4-py3.5.egg/kerncraft/headers/dummy.c kernels/himeno.c_compilable.c -Ofast -xCORE-AVX2 -fno-alias -std=c99 -I/home/hpc/unrz/unrz55/programming/py/venv/lib/python3.5/site-packages/kerncraft-0.6.4-py3.5.egg/kerncraft/headers/ -I/mnt/opt/likwid-4.3.1/include -llikwid -L/mnt/opt/likwid-4.3.1/lib -pthread -o /home/hpc/unrz/unrz55/programming/py/kerncraft/examples/kernels/himeno.likwid_marked
Traceback (most recent call last):
  File "/home/hpc/unrz/unrz55/programming/py/venv/bin/kerncraft", line 11, in <module>
    load_entry_point('kerncraft==0.6.4', 'console_scripts', 'kerncraft')()
  File "/home/hpc/unrz/unrz55/programming/py/venv/lib/python3.5/site-packages/kerncraft-0.6.4-py3.5.egg/kerncraft/kerncraft.py", line 284, in main
    run(parser, args)
  File "/home/hpc/unrz/unrz55/programming/py/venv/lib/python3.5/site-packages/kerncraft-0.6.4-py3.5.egg/kerncraft/kerncraft.py", line 250, in run
    model.analyze()
  File "/home/hpc/unrz/unrz55/programming/py/venv/lib/python3.5/site-packages/kerncraft-0.6.4-py3.5.egg/kerncraft/models/benchmark.py", line 315, in analyze
    repetitions = self.iterations / 10
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

```
