### ISSUE TITLE
Cache simulation uses too much memory

### ISSUE THREAD

**Issue by sguera** [RRZE-HPC/kerncraft#97]
Command executed:

```
kerncraft -P LC -p Roofline -p ECM /home/hpc/ihpc/ihpc07/THESIS/stempelvalidation/stencils/3D/2r/point-symmetric/star/variable/3d-2r-point-symmetric-variable-star-stencil.c -m IvyBridgeEP_E5-2660v2.yml -D M 500 -D N 500 -D P 500 --unit=FLOP/s --cores=10 -vv
```

Error:

```
Traceback (most recent call last):
  File "/home/hpc/ihpc/ihpc07/miniconda2/envs/kern0610/bin/kerncraft", line 11, in <module>
    sys.exit(main())
  File "/home/hpc/ihpc/ihpc07/miniconda2/envs/kern0610/lib/python3.5/site-packages/kerncraft/kerncraft.py", line 289, in main
    run(parser, args)
  File "/home/hpc/ihpc/ihpc07/miniconda2/envs/kern0610/lib/python3.5/site-packages/kerncraft/kerncraft.py", line 253, in run
    model = getattr(models, model_name)(kernel, machine, args, parser)
  File "/home/hpc/ihpc/ihpc07/miniconda2/envs/kern0610/lib/python3.5/site-packages/kerncraft/models/roofline.py", line 50, in __init__
    self.predictor = LayerConditionPredictor(self.kernel, self.machine, self.cores)
  File "/home/hpc/ihpc/ihpc07/miniconda2/envs/kern0610/lib/python3.5/site-packages/kerncraft/cacheprediction.py", line 101, in __init__
    "Problematic term: {}.".format(t))
ValueError: Number of multiplications in index term does not match loop counter order. Problematic term: 7*N*P*k.
```

The machine file is available in kerncraft. The stencil code is:
```
double a[M][N][P];
double b[M][N][P];
double W[M][N][P][7];

for(int k=2; k < M-2; k++){
for(int j=2; j < N-2; j++){
for(int i=2; i < P-2; i++){
b[k][j][i] = W[k][j][i][0] * a[k][j][i]
+ W[k][j][i][1] * (a[k][j][i-1] + a[k][j][i+1])
+ W[k][j][i][2] * (a[k-1][j][i] + a[k+1][j][i])
+ W[k][j][i][3] * (a[k][j-1][i] + a[k][j+1][i])
+ W[k][j][i][4] * (a[k][j][i-2] + a[k][j][i+2])
+ W[k][j][i][5] * (a[k-2][j][i] + a[k+2][j][i])
+ W[k][j][i][6] * (a[k][j-2][i] + a[k][j+2][i])
;
}
}
}
```

The same code also fails when using Simulation instead of LC. In that case, the job gets killed at some point.

**Comment by cod3monk** [comment]
This is a known limitation of the LC model and not a bug.

In case of the cache simulation: it goes haywire and uses all available memory (on my machine it tried to use more than 55GB). This needs some further investigation to fix this issue.

**Comment by sguera** [comment]
What about when using the Simulation model? I do not get any error from kerncraft, but the job gets killed. Is it also due to memory overuse?

**Comment by sguera** [comment]
An additional information for you:

If I use ```--cores=1``` it completes successfully.
